zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  ignored-services: "*"
  routes:
     categories:
      path: /categories/**
      serviceId: category-server
      strip-prefix: true
     products:
      path: /products
      serviceId: product-server
      strip-prefix: true
